### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by crak3rjack** [t43pasdf/plugin.video.espn_3#2]
The addon is broken wont open

**Comment by usphil** [comment]
The favorite link ESPN channels from addon are working but got error when click to open the addon. 
@t43pasdf, could you take a look on this issue, below is kodi.log:

2020-03-11 17:35:15.469 T:2793468800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.espn_3/addon.py", line 41, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.espn_3/resources/lib/plugin.py", line 221, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.espn_3/resources/lib/plugin.py", line 135, in new_index
                                                parse_json(WATCH_API_V3_LIVE)
                                              File "/storage/.kodi/addons/plugin.video.espn_3/resources/lib/page_api.py", line 108, in parse_json
                                                json_data = util.get_url_as_json_cache(get_v3_url(url))
                                              File "/storage/.kodi/addons/plugin.video.espn_3/resources/lib/util.py", line 120, in get_url_as_json_cache
                                                raise e
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-03-11 17:35:16.129 T:2801861504   ERROR: GetDirectory - Error getting plugin://plugin.video.espn_3/
2020-03-11 17:35:16.153 T:3156206464   ERROR: EXCEPTION: XBMC is not playing any file
2020-03-11 17:35:16.169 T:4060262416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.espn_3/) failed
